name: .NET Build and Test Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del codice
      uses: actions/checkout@v2

    - name: Configurazione dell'ambiente .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0'  # Sostituisci con la versione di .NET che stai usando

    - name: Ripristino delle dipendenze NuGet
      run: dotnet restore

    - name: Compilazione della soluzione
      run: dotnet build --no-restore

    - name: Esecuzione dei test
      run: dotnet test --no-build --fail-on-error

    - name: Termina con errore se i test falliscono
      if: failure()
      run: exit 1
